version: '2'

services:
  bokeh:
    restart: always
    build:
      context: .
    image: molecular-data-explorer:master
    environment:
      BOKEH_PREFIX: ""
      SHELL: '/bin/bash'

    volumes:
     - './examples:/app/examples'
    ports:
      - '8060:8060'
